services:
  nginx:
    image: nginx:alpine
    ports:
      - "5643:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${DEPLOYMENT_TARGET}
        NEXT_PUBLIC_SITE_URL: ${DEPLOYMENT_TARGET}
    env_file:
      - .env
    depends_on:
      - backend

  backend: &backend-base
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        CORS_ORIGIN: ${DEPLOYMENT_TARGET}
    image: digital-suits/backend:latest
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/digital_suits
    depends_on:
      - db
    command: [ "node", "dist/index.js" ]

  db-sync:
    <<: *backend-base
    command: [ "node", "dist/db-sync.js" ]

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=digital_suits
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
